const repl = require('repl');
repl.start({
  prompt: 'qinliang> ',
  input: process.stdin,
  output: process.stdout,
  //其中name就是我们输入的命令，context是一个全局对象,filename就是固定的"repl"字符串，callback是一个函数签名[function finish]
  eval:function(cmd, context, filename, callback) {
 		//console.log(cmd);
 	     //打印name
 		//console.log(context);
 		//其中context就是如下的格式：很显然这是一个全局对象有process,Buffer,require，module,console等
 		/*
		{ DTRACE_NET_SERVER_CONNECTION: [Function],
		  DTRACE_NET_STREAM_END: [Function],
		  DTRACE_HTTP_SERVER_REQUEST: [Function],
		  DTRACE_HTTP_SERVER_RESPONSE: [Function],
		  DTRACE_HTTP_CLIENT_REQUEST: [Function],
		  DTRACE_HTTP_CLIENT_RESPONSE: [Function],
		  COUNTER_NET_SERVER_CONNECTION: [Function],
		  COUNTER_NET_SERVER_CONNECTION_CLOSE: [Function],
		  COUNTER_HTTP_SERVER_REQUEST: [Function],
		  COUNTER_HTTP_SERVER_RESPONSE: [Function],
		  COUNTER_HTTP_CLIENT_REQUEST: [Function],
		  COUNTER_HTTP_CLIENT_RESPONSE: [Function],
		  global: [Circular],
		  process:
		   process {
		     title: '5s�p@',
		     version: 'v4.4.1',
		     moduleLoadList:
		      [ 'Binding contextify',
		        'Binding natives',
		        'NativeModule events',
		        'NativeModule buffer',
		        'Binding buffer',
		        'NativeModule internal/util',
		        'Binding util',
		        'NativeModule timers',
		        'Binding timer_wrap',
		        'NativeModule _linklist',
		        'NativeModule assert',
		        'NativeModule util',
		        'Binding uv',
		        'NativeModule path',
		        'NativeModule module',
		        'NativeModule internal/module',
		        'NativeModule vm',
		        'NativeModule fs',
		        'Binding fs',
		        'NativeModule constants',
		        'Binding constants',
		        'NativeModule stream',
		        'NativeModule _stream_readable',
		        'NativeModule _stream_writable',
		        'NativeModule _stream_duplex',
		        'NativeModule _stream_transform',
		        'NativeModule _stream_passthrough',
		        'Binding fs_event_wrap',
		        'NativeModule repl',
		        'NativeModule readline',
		        'NativeModule console',
		        'Binding tty_wrap',
		        'NativeModule tty',
		        'NativeModule net',
		        'NativeModule internal/net',
		        'Binding cares_wrap',
		        'Binding tcp_wrap',
		        'Binding pipe_wrap',
		        'Binding stream_wrap',
		        'Binding signal_wrap',
		        'NativeModule domain',
		        'NativeModule string_decoder' ],
		     versions:
		      { http_parser: '2.5.2',
		        node: '4.4.1',
		        v8: '4.5.103.35',
		        uv: '1.8.0',
		        zlib: '1.2.8',
		        ares: '1.10.1-DEV',
		        icu: '56.1',
		        modules: '46',
		        openssl: '1.0.2g' },
		     arch: 'ia32',
		     platform: 'win32',
		     release:
		      { name: 'node',
		        lts: 'Argon',
		        sourceUrl: 'https://nodejs.org/download/release/v4.4.1/node-v4.4.1.tar.g
		z',
		        headersUrl: 'https://nodejs.org/download/release/v4.4.1/node-v4.4.1-head
		ers.tar.gz',
		        libUrl: 'https://nodejs.org/download/release/v4.4.1/win-x86/node.lib' },

		     argv:
		      [ 'C:\\Program Files\\nodejs\\node.exe',
		        'C:\\Users\\Administrator\\Desktop\\N-blog\\fiboo\\repl2' ],
		     execArgv: [],
		     env:
		      { ACLOCAL_PATH: '/mingw32/share/aclocal:/usr/share/aclocal',
		        ALLUSERSPROFILE: 'C:\\ProgramData',
		        APPDATA: 'C:\\Users\\Administrator\\AppData\\Roaming',
		        CLASSPATH: 'C:\\Program Files\\Java\\jdk1.6.0_01\\lib\\tools.jar;C:\\Pro
		gram Files\\Java\\jdk1.6.0_01\\lib\\dt.jar;',
		        COMMONPROGRAMFILES: 'C:\\Program Files\\Common Files',
		        COMPUTERNAME: 'WIN7-20140901YQ',
		        COMSPEC: 'C:\\Windows\\system32\\cmd.exe',
		        DISPLAY: 'needs-to-be-defined',
		        EXEPATH: 'C:\\Program Files\\Git',
		        FP_NO_HOST_CHECK: 'NO',
		        HOME: 'C:\\Users\\Administrator',
		        HOMEDRIVE: 'C:',
		        HOMEPATH: '\\Users\\Administrator',
		        HOSTNAME: 'WIN7-20140901YQ',
		        INFOPATH: '/usr/local/info:/usr/share/info:/usr/info:/share/info:',
		        JAVA_HOME: 'C:\\Program Files\\Java\\jdk1.6.0_01;',
		        LANG: 'zh_CN.UTF-8',
		        LOCALAPPDATA: 'C:\\Users\\Administrator\\AppData\\Local',
		        LOGONSERVER: '\\\\WIN7-20140901YQ',
		        MANPATH: '/mingw32/share/man:/usr/local/man:/usr/share/man:/usr/man:/sha
		re/man:',
		        MSYSTEM: 'MINGW32',
		        NUMBER_OF_PROCESSORS: '2',
		        OPENSSL_CONF: 'C:\\OpenSSL-Win32\\bin\\openssl.cfg',
		        OS: 'Windows_NT',
		        PATH: 'C:\\Users\\Administrator\\bin;C:\\Program Files\\Git\\mingw32\\bi
		n;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\P
		rogram Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw32\\bin;C:\\Program Fil
		es\\Git\\usr\\bin;C:\\Users\\Administrator\\bin;C:\\Windows\\system32;C:\\Window
		s;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\
		\Program Files\\Java\\jdk1.6.0_01\\bin;C:\\Program Files\\Java\\jre1.6.0_01\\bin
		;C:\\Program Files\\Microsoft SQL Server\\100\\Tools\\Binn;C:\\Program Files\\Mi
		crosoft SQL Server\\100\\DTS\\Binn;C:\\Program Files\\Microsoft SQL Server\\100\
		\Tools\\Binn\\VSShell\\Common7\\IDE;C:\\Program Files\\Microsoft Visual Studio 9
		.0\\Common7\\IDE\\PrivateAssemblies;C:\\Program Files\\MySQL\\MySQL Server 5.5\\
		bin;C:\\Program Files\\nodejs;C:\\Users\\Administrator\\AppData\\Roaming\\npm;C:
		\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\co
		re_perl',
		        PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
		        PKG_CONFIG_PATH: '/mingw32/lib/pkgconfig:/mingw32/share/pkgconfig',
		        PLINK_PROTOCOL: 'ssh',
		        PRINTER: '\\\\510SERVER\\Canon LBP2900',
		        PROCESSOR_ARCHITECTURE: 'x86',
		        PROCESSOR_IDENTIFIER: 'x86 Family 15 Model 4 Stepping 7, GenuineIntel',
		        PROCESSOR_LEVEL: '15',
		        PROCESSOR_REVISION: '0407',
		        ProgramData: 'C:\\ProgramData',
		        PROGRAMFILES: 'C:\\Program Files',
		        PS1: '\\[\\033]0;$TITLEPREFIX:${PWD//[^[:ascii:]]/?}\\007\\]\\n\\[\\033[
		32m\\]\\u@\\h \\[\\033[35m\\]$MSYSTEM \\[\\033[33m\\]\\w\\[\\033[36m\\]`__git_ps
		1`\\[\\033[0m\\]\\n$ ',
		        PSModulePath: 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\
		',
		        PUBLIC: 'C:\\Users\\Public',
		        PWD: '/c/Users/Administrator/Desktop/N-blog/fiboo',
		        SESSIONNAME: 'Console',
		        SHELL: 'C:\\Program Files\\Git\\usr\\bin\\bash',
		        SHLVL: '1',
		        SSH_ASKPASS: '/mingw32/libexec/git-core/git-gui--askpass',
		        SYSTEMDRIVE: 'C:',
		        SYSTEMROOT: 'C:\\Windows',
		        TEMP: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
		        TERM: 'xterm',
		        TMP: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
		        TMPDIR: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
		        USERDOMAIN: 'WIN7-20140901YQ',
		        USERNAME: 'Administrator',
		        USERPROFILE: 'C:\\Users\\Administrator',
		        WINDIR: 'C:\\Windows',
		        windows_tracing_flags: '3',
		        windows_tracing_logfile: 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.
		log',
		        _: '/usr/bin/winpty' },
		     pid: 6464,
		     features:
		      { debug: false,
		        uv: true,
		        ipv6: true,
		        tls_npn: true,
		        tls_sni: true,
		        tls_ocsp: true,
		        tls: true },
		     _needImmediateCallback: false,
		     execPath: 'C:\\Program Files\\nodejs\\node.exe',
		     debugPort: 5858,
		     _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
		     _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
		     _getActiveRequests: [Function: _getActiveRequests],
		     _getActiveHandles: [Function: _getActiveHandles],
		     reallyExit: [Function: reallyExit],
		     abort: [Function: abort],
		     chdir: [Function: chdir],
		     cwd: [Function: cwd],
		     umask: [Function: umask],
		     _kill: [Function: _kill],
		     _debugProcess: [Function: _debugProcess],
		     _debugPause: [Function: _debugPause],
		     _debugEnd: [Function: _debugEnd],
		     hrtime: [Function: hrtime],
		     dlopen: [Function: dlopen],
		     uptime: [Function: uptime],
		     memoryUsage: [Function: memoryUsage],
		     binding: [Function: binding],
		     _linkedBinding: [Function: _linkedBinding],
		     _events:
		      { newListener: [Function],
		        removeListener: [Function],
		        SIGWINCH: [Object] },
		     _rawDebug: [Function],
		     _eventsCount: 3,
		     domain: [Getter/Setter],
		     _maxListeners: undefined,
		     EventEmitter:
		      { [Function: EventEmitter]
		        EventEmitter: [Circular],
		        usingDomains: true,
		        defaultMaxListeners: 10,
		        init: [Function],
		        listenerCount: [Function] },
		     _fatalException: [Function],
		     _exiting: false,
		     assert: [Function],
		     config: { target_defaults: [Object], variables: [Object] },
		     nextTick: [Function: nextTick],
		     _tickCallback: [Function: _tickDomainCallback],
		     _tickDomainCallback: [Function: _tickDomainCallback],
		     stdout: [Getter],
		     stderr: [Getter],
		     stdin: [Getter],
		     openStdin: [Function],
		     exit: [Function],
		     kill: [Function],
		     mainModule:
		      Module {
		        id: '.',
		        exports: {},
		        parent: null,
		        filename: 'C:\\Users\\Administrator\\Desktop\\N-blog\\fiboo\\repl2.js',
		        loaded: true,
		        children: [],
		        paths: [Object] } },
		  GLOBAL:
		   { DTRACE_NET_SERVER_CONNECTION: [Function],
		     DTRACE_NET_STREAM_END: [Function],
		     DTRACE_HTTP_SERVER_REQUEST: [Function],
		     DTRACE_HTTP_SERVER_RESPONSE: [Function],
		     DTRACE_HTTP_CLIENT_REQUEST: [Function],
		     DTRACE_HTTP_CLIENT_RESPONSE: [Function],
		     COUNTER_NET_SERVER_CONNECTION: [Function],
		     COUNTER_NET_SERVER_CONNECTION_CLOSE: [Function],
		     COUNTER_HTTP_SERVER_REQUEST: [Function],
		     COUNTER_HTTP_SERVER_RESPONSE: [Function],
		     COUNTER_HTTP_CLIENT_REQUEST: [Function],
		     COUNTER_HTTP_CLIENT_RESPONSE: [Function],
		     global: [Circular],
		     process:
		      process {
		        title: 'P�1',
		        version: 'v4.4.1',
		        moduleLoadList: [Object],
		        versions: [Object],
		        arch: 'ia32',
		        platform: 'win32',
		        release: [Object],
		        argv: [Object],
		        execArgv: [],
		        env: [Object],
		        pid: 6464,
		        features: [Object],
		        _needImmediateCallback: false,
		        execPath: 'C:\\Program Files\\nodejs\\node.exe',
		        debugPort: 5858,
		        _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
		        _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
		        _getActiveRequests: [Function: _getActiveRequests],
		        _getActiveHandles: [Function: _getActiveHandles],
		        reallyExit: [Function: reallyExit],
		        abort: [Function: abort],
		        chdir: [Function: chdir],
		        cwd: [Function: cwd],
		        umask: [Function: umask],
		        _kill: [Function: _kill],
		        _debugProcess: [Function: _debugProcess],
		        _debugPause: [Function: _debugPause],
		        _debugEnd: [Function: _debugEnd],
		        hrtime: [Function: hrtime],
		        dlopen: [Function: dlopen],
		        uptime: [Function: uptime],
		        memoryUsage: [Function: memoryUsage],
		        binding: [Function: binding],
		        _linkedBinding: [Function: _linkedBinding],
		        _events: [Object],
		        _rawDebug: [Function],
		        _eventsCount: 3,
		        domain: [Getter/Setter],
		        _maxListeners: undefined,
		        EventEmitter: [Object],
		        _fatalException: [Function],
		        _exiting: false,
		        assert: [Function],
		        config: [Object],
		        nextTick: [Function: nextTick],
		        _tickCallback: [Function: _tickDomainCallback],
		        _tickDomainCallback: [Function: _tickDomainCallback],
		        stdout: [Getter],
		        stderr: [Getter],
		        stdin: [Getter],
		        openStdin: [Function],
		        exit: [Function],
		        kill: [Function],
		        mainModule: [Object] },
		     GLOBAL: [Circular],
		     root: [Circular],
		     Buffer:
		      { [Function: Buffer]
		        poolSize: 8192,
		        isBuffer: [Function: isBuffer],
		        compare: [Function: compare],
		        isEncoding: [Function],
		        concat: [Function],
		        byteLength: [Function: byteLength] },
		     clearImmediate: [Function],
		     clearInterval: [Function],
		     clearTimeout: [Function],
		     setImmediate: [Function],
		     setInterval: [Function],
		     setTimeout: [Function],
		     console: [Getter] },
		  root:
		   { DTRACE_NET_SERVER_CONNECTION: [Function],
		     DTRACE_NET_STREAM_END: [Function],
		     DTRACE_HTTP_SERVER_REQUEST: [Function],
		     DTRACE_HTTP_SERVER_RESPONSE: [Function],
		     DTRACE_HTTP_CLIENT_REQUEST: [Function],
		     DTRACE_HTTP_CLIENT_RESPONSE: [Function],
		     COUNTER_NET_SERVER_CONNECTION: [Function],
		     COUNTER_NET_SERVER_CONNECTION_CLOSE: [Function],
		     COUNTER_HTTP_SERVER_REQUEST: [Function],
		     COUNTER_HTTP_SERVER_RESPONSE: [Function],
		     COUNTER_HTTP_CLIENT_REQUEST: [Function],
		     COUNTER_HTTP_CLIENT_RESPONSE: [Function],
		     global: [Circular],
		     process:
		      process {
		        title: '',
		        version: 'v4.4.1',
		        moduleLoadList: [Object],
		        versions: [Object],
		        arch: 'ia32',
		        platform: 'win32',
		        release: [Object],
		        argv: [Object],
		        execArgv: [],
		        env: [Object],
		        pid: 6464,
		        features: [Object],
		        _needImmediateCallback: false,
		        execPath: 'C:\\Program Files\\nodejs\\node.exe',
		        debugPort: 5858,
		        _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
		        _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
		        _getActiveRequests: [Function: _getActiveRequests],
		        _getActiveHandles: [Function: _getActiveHandles],
		        reallyExit: [Function: reallyExit],
		        abort: [Function: abort],
		        chdir: [Function: chdir],
		        cwd: [Function: cwd],
		        umask: [Function: umask],
		        _kill: [Function: _kill],
		        _debugProcess: [Function: _debugProcess],
		        _debugPause: [Function: _debugPause],
		        _debugEnd: [Function: _debugEnd],
		        hrtime: [Function: hrtime],
		        dlopen: [Function: dlopen],
		        uptime: [Function: uptime],
		        memoryUsage: [Function: memoryUsage],
		        binding: [Function: binding],
		        _linkedBinding: [Function: _linkedBinding],
		        _events: [Object],
		        _rawDebug: [Function],
		        _eventsCount: 3,
		        domain: [Getter/Setter],
		        _maxListeners: undefined,
		        EventEmitter: [Object],
		        _fatalException: [Function],
		        _exiting: false,
		        assert: [Function],
		        config: [Object],
		        nextTick: [Function: nextTick],
		        _tickCallback: [Function: _tickDomainCallback],
		        _tickDomainCallback: [Function: _tickDomainCallback],
		        stdout: [Getter],
		        stderr: [Getter],
		        stdin: [Getter],
		        openStdin: [Function],
		        exit: [Function],
		        kill: [Function],
		        mainModule: [Object] },
		     GLOBAL: [Circular],
		     root: [Circular],
		     Buffer:
		      { [Function: Buffer]
		        poolSize: 8192,
		        isBuffer: [Function: isBuffer],
		        compare: [Function: compare],
		        isEncoding: [Function],
		        concat: [Function],
		        byteLength: [Function: byteLength] },
		     clearImmediate: [Function],
		     clearInterval: [Function],
		     clearTimeout: [Function],
		     setImmediate: [Function],
		     setInterval: [Function],
		     setTimeout: [Function],
		     console: [Getter] },
		  Buffer:
		   { [Function: Buffer]
		     poolSize: 8192,
		     isBuffer: [Function: isBuffer],
		     compare: [Function: compare],
		     isEncoding: [Function],
		     concat: [Function],
		     byteLength: [Function: byteLength] },
		  clearImmediate: [Function],
		  clearInterval: [Function],
		  clearTimeout: [Function],
		  setImmediate: [Function],
		  setInterval: [Function],
		  setTimeout: [Function],
		  console:
		   Console {
		     log: [Function: bound ],
		     info: [Function: bound ],
		     warn: [Function: bound ],
		     error: [Function: bound ],
		     dir: [Function: bound ],
		     time: [Function: bound ],
		     timeEnd: [Function: bound ],
		     trace: [Function: bound trace],
		     assert: [Function: bound ] },
		  module:
		   Module {
		     id: '<repl>',
		     exports: {},
		     parent: undefined,
		     filename: null,
		     loaded: false,
		     children: [],
		     paths:
		      [ 'C:\\Users\\Administrator\\Desktop\\N-blog\\fiboo\\repl\\node_modules',
		        'C:\\Users\\Administrator\\Desktop\\N-blog\\fiboo\\node_modules',
		        'C:\\Users\\Administrator\\Desktop\\N-blog\\node_modules',
		        'C:\\Users\\Administrator\\Desktop\\node_modules',
		        'C:\\Users\\Administrator\\node_modules',
		        'C:\\Users\\node_modules',
		        'C:\\node_modules',
		        'C:\\Users\\Administrator\\.node_modules',
		        'C:\\Users\\Administrator\\.node_libraries',
		        'C:\\Program Files\\lib\\node' ] },
		  require:
		   { [Function: require]
		     resolve: [Function],
		     main:
		      Module {
		        id: '.',
		        exports: {},
		        parent: null,
		        filename: 'C:\\Users\\Administrator\\Desktop\\N-blog\\fiboo\\repl2.js',
		        loaded: true,
		        children: [],
		        paths: [Object] },
		     extensions: { '.js': [Function], '.json': [Function], '.node': [Function] }
		,
		     cache: { 'C:\Users\Administrator\Desktop\N-blog\fiboo\repl2.js': [Object] }
		 } }

 		*/
 		//console.log(filename);
 	//这里一直指的是repl，也就是我们引入的repl模块把
 		//console.log(callback);
   //这里是[Function: finish]
	}
});
//这时候我们输入node repl2我们看看cmd, context, filename, callback分别表示的是什么
